
version: '3'

services:
  postgres:
    image: postgres:latest
    
    restart: always
    ports:
      - "5432:5432"  # Mengaitkan port lokal ke port PostgreSQL
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

